server:
  port: 8085

spring:
  application:
    name: commande-service
  datasource:
    url: jdbc:mysql://localhost:3306/commande-bd
    username: anwar
    password: anaanwar
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10